### PR TITLE
PullAndPullMembersDownFromInterfaceToInterface

### PR DESCRIPTION
**Pull request by as3boyan**
Testing IDEA Pull Requests
More complete implementation will be a lil bit later

### CODE REVIEW

**Comment by as3boyan** [comment]
Ok, this case should be handled fine. Still having formatting issues. Also need to test how classes and fields work with this feature.

**Comment by as3boyan** [comment]
Also got problem with this:

AbstractHaxePsiClass
```
@Override
   public PsiElement add(@NotNull PsiElement element) throws IncorrectOperationException {
    //Not sure, sometimes PsiTree won't get updated after this change and remains incorrect
    //if (getRBrace() != null) {
    //  return addBefore(element, getRBrace());
    //}
    //else {
    //  return super.add(element);
    //}

    return super.add(element);
  }
```

Commented code works, but not that great, Psi Structure won't update after that change.

It updates only when I do something, like typing or undo/redo, another action

**Comment by as3boyan** [comment]
The thing is that I need to add for example method to class

**Comment by EBatTiVo** [comment]
>  Psi Structure won't update after that change.
>
> It updates only when I do something, like typing or undo/redo, another action

Are you sure that you are running on the UI/AWT thread when updating?  It may be that the underlying PSI won't really be accessible unless you are.  (Meaning, that sometimes getting the PSI for an editor gives you a /copy/ -- or a version of the PSI with copy-on-write semantics -- when you are running in a worker thread.  I don't know for sure that it does, but I have seen some code that leads me to that belief.)

**Comment by EBatTiVo** [comment]
Boyan, if you're happy with this change, you can pull it, and then merge it up to the TiVo/intellij-haxe fork.  If you're not, then we'll wait for you to finish it before we delete this (ebattivo) fork.

**Comment by as3boyan** [comment]
>Are you sure that you are running on the UI/AWT thread when updating? It may be that the underlying PSI won't really be accessible unless you are. (Meaning, that sometimes getting the PSI for an editor gives you a /copy/ -- or a version of the PSI with copy-on-write semantics -- when you are running in a worker thread. I don't know for sure that it does, but I have seen some code that leads me to that belief.)

I tried to do this in a same way it's implemented for Java(you seen parts of code from intellij-community), I think in Java it calls `add` on `PsiClass` instance, which is target class(in our case it's AbstractHaxePsiClass), it adds method/field to the body, not just below class(like we have in Haxe)

And if I override add, like I did before, Psi remains incorrect, but with original `add` Psi updates fine.
And I don't get it, it should reparse it...

>Are you sure that you are running on the UI/AWT thread when updating? It may be that the underlying PSI won't really be accessible unless you are. (Meaning, that sometimes getting the PSI for an editor gives you a /copy/ -- or a version of the PSI with copy-on-write semantics -- when you are running in a worker thread. I don't know for sure that it does, but I have seen some code that leads me to that belief.)

I had such issues when I was working on HaxelibManager

**Comment by as3boyan** [comment]
It's weird, but it works using `(PsiMember)myTargetSuperClass.addBefore(methodCopy, myTargetSuperClass.getRBrace())`

**Comment by as3boyan** [comment]
I got wierd issues with IDEA 13.1.6, sometimes IntelliJ IDEA SDK sourcepaths disappears in project options, and just JDK sourcepaths

**Comment by EBatTiVo** [comment]
I like this change.  I was just reading the implementation for add(), and it *should* have devolved to addBefore(myTargetClass.getFirstChildElement()).  But there is room for error in that scenario (though if getRBrace() fails, it will be the same as simply calling add, and it will still fail.  So, for classes that have the form:
```haxe
class B extends A
    new () : void {
        ...
    }
```
where the class doesn't have braces, we will have to add the wrapping braces as well.

Feel free to pull this when you are happy with it.  I think it looks pretty good (though I haven't tested it).

**Comment by as3boyan** [comment]
Seems like so. Then it should check if class has body. Thanks.

**Comment by EBatTiVo** [comment]
Not just a body; the example I gave still has a body in the PSI.  We specifically have to check for the existence of curly braces and add them around the body, if none previously exist.

I think we have this problem for all of the extract/pull/push type operations.

**Pull request merged**
